package com.casic.patrol.keyvalue.persistence.domain;

// Generated by Hibernate Tools

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HtHumantask 人工任务.
 * 
 * @author Lingo
 */
@Entity
@Table(name = "KV_PROP")
@SequenceGenerator(name = "CD_SEQ_KV_PROP",sequenceName = "CD_SEQ_KV_PROP",allocationSize = 1,initialValue = 1)
public class KVProp implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;
    private String code;
    private int type;
    private String value;
    private String tenantID;
    private KVRecord kvRecord;



    public KVProp() {
    }

    /** @return 主键. */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CD_SEQ_KV_PROP")
    @Column(name = "DBID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }
    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "CODE")
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "TYPE")
    public int getType() {
        return type;
    }
    public void setType(int type) {
        this.type = type;
    }

    @Column(name = "PROP_VALUE")
    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Column(name = "TENANTID")
    public String getTenantID() {
        return tenantID;
    }

    public void setTenantID(String tenantID) {
        this.tenantID = tenantID;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RECORD_ID")
    public KVRecord getKvRecord() {
        return kvRecord;
    }

    public void setKvRecord(KVRecord kvRecord) {
        this.kvRecord = kvRecord;
    }
}
