package com.casic.patrol.keyvalue.persistence.domain;

// Generated by Hibernate Tools

import com.casic.patrol.humantask.persistence.domain.HtParticipant;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HtHumantask 人工任务.
 * 
 * @author Lingo
 */
@Entity
@Table(name = "KV_RECORD")
@SequenceGenerator(name = "CD_SEQ_KV_RECORD",sequenceName = "CD_SEQ_KV_RECORD",allocationSize = 1,initialValue = 1)
public class KVRecord implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;
    private String category;
    private int status;
    private String ref;
    private String userID;
    private Date createTime;
    private String name;
    private String formTemplateCode;
    private String tennantID;
    /** . */
    private Set<KVProp> kvProps = new HashSet<KVProp>(0);

    public KVRecord() {
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "kvRecord")
    public Set<KVProp> getKvProps() {
        return kvProps;
    }

    public void setKvProps(Set<KVProp> kvProps) {
        this.kvProps = kvProps;
    }

    /** @return 主键. */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CD_SEQ_KV_RECORD")
    @Column(name = "DBID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }
    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "CATEGORY")
    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    @Column(name = "STATUS")
    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    @Column(name = "REF")
    public String getRef() {
        return ref;
    }

    public void setRef(String ref) {
        this.ref = ref;
    }

    @Column(name = "USERID")
    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    @Column(name = "CREATETIME")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name = "KV_RECORD_NAME")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "FORMTEMPLATECODE")
    public String getFormTemplateCode() {
        return formTemplateCode;
    }

    public void setFormTemplateCode(String formTemplateCode) {
        this.formTemplateCode = formTemplateCode;
    }

    @Column(name = "TENANTID")
    public String getTennantID() {
        return tennantID;
    }

    public void setTennantID(String tennantID) {
        this.tennantID = tennantID;
    }
}
