package com.casic.patrol.bpm.persistence.domain;

// Generated by Hibernate Tools

import javax.persistence.*;

/**
 * BpmConfRule 配置规则（暂时未用）.
 * 
 * @author Lingo
 */
@Entity
@Table(name = "BPM_CONF_RULE")
@SequenceGenerator(name = "CD_SEQ_BPM_CONF_RULE",sequenceName = "CD_SEQ_BPM_CONF_RULE",allocationSize = 1,initialValue = 1)
public class BpmConfRule implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;

    /** 外键，配置节点. */
    private BpmConfNode bpmConfNode;

    /** 值. */
    private String value;

    public BpmConfRule() {
    }

    public BpmConfRule(Long id) {
        this.id = id;
    }

    public BpmConfRule(Long id, BpmConfNode bpmConfNode, String value) {
        this.id = id;
        this.bpmConfNode = bpmConfNode;
        this.value = value;
    }

    /** @return 主键. */
    @Id
    @Column(name = "DBID", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CD_SEQ_BPM_CONF_RULE")
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return 外键，配置节点. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NODE_ID")
    public BpmConfNode getBpmConfNode() {
        return this.bpmConfNode;
    }

    /**
     * @param bpmConfNode
     *            外键，配置节点.
     */
    public void setBpmConfNode(BpmConfNode bpmConfNode) {
        this.bpmConfNode = bpmConfNode;
    }

    /** @return 值. */
    @Column(name = "VALUE", length = 200)
    public String getValue() {
        return this.value;
    }

    /**
     * @param value
     *            值.
     */
    public void setValue(String value) {
        this.value = value;
    }
}
