package com.casic.patrol.bpm.persistence.domain;

// Generated by Hibernate Tools

import javax.persistence.*;

/**
 * BpmConfAssign .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "BPM_CONF_ASSIGN")
@SequenceGenerator(name = "CD_SEQ_BPM_CONFASSIGN",sequenceName = "CD_SEQ_BPM_CONFASSIGN",allocationSize = 1,initialValue = 1)
public class BpmConfAssign implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private BpmConfNode bpmConfNode;

    /** null. */
    private String name;

    public BpmConfAssign() {
    }

    public BpmConfAssign(Long id) {
        this.id = id;
    }

    public BpmConfAssign(Long id, BpmConfNode bpmConfNode, String name) {
        this.id = id;
        this.bpmConfNode = bpmConfNode;
        this.name = name;
    }

    /** @return null. */
    @Id
    @Column(name = "DBID", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CD_SEQ_BPM_CONFASSIGN")
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NODE_ID")
    public BpmConfNode getBpmConfNode() {
        return this.bpmConfNode;
    }

    /**
     * @param bpmConfNode
     *            null.
     */
    public void setBpmConfNode(BpmConfNode bpmConfNode) {
        this.bpmConfNode = bpmConfNode;
    }

    /** @return null. */
    @Column(name = "NAME", length = 50)
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            null.
     */
    public void setName(String name) {
        this.name = name;
    }
}
