package com.casic.patrol.bpm.persistence.domain;

// Generated by Hibernate Tools

import javax.persistence.*;

/**
 * BpmTaskDefNotice .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "BPM_TASK_DEF_NOTICE")
@SequenceGenerator(name = "CD_SEQ_BPM_TASK_DEF_NOTICE",sequenceName = "CD_SEQ_BPM_TASK_DEF_NOTICE",allocationSize = 1,initialValue = 1)
public class BpmTaskDefNotice implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private BpmMailTemplate bpmMailTemplate;

    /** null. */
    private BpmProcess bpmProcess;

    /** null. */
    private String taskDefinitionKey;

    /** null. */
    private Integer type;

    /** null. */
    private String receiver;

    /** null. */
    private String dueDate;

    public BpmTaskDefNotice() {
    }

    public BpmTaskDefNotice(Long id) {
        this.id = id;
    }

    public BpmTaskDefNotice(Long id, BpmMailTemplate bpmMailTemplate,
            BpmProcess bpmProcess, String taskDefinitionKey, Integer type,
            String receiver, String dueDate) {
        this.id = id;
        this.bpmMailTemplate = bpmMailTemplate;
        this.bpmProcess = bpmProcess;
        this.taskDefinitionKey = taskDefinitionKey;
        this.type = type;
        this.receiver = receiver;
        this.dueDate = dueDate;
    }

    /** @return null. */
    @Id
    @Column(name = "DBID", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CD_SEQ_BPM_TASK_DEF_NOTICE")
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TEMPLATE_ID")
    public BpmMailTemplate getBpmMailTemplate() {
        return this.bpmMailTemplate;
    }

    /**
     * @param bpmMailTemplate
     *            null.
     */
    public void setBpmMailTemplate(BpmMailTemplate bpmMailTemplate) {
        this.bpmMailTemplate = bpmMailTemplate;
    }

    /** @return null. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PROCESS_ID")
    public BpmProcess getBpmProcess() {
        return this.bpmProcess;
    }

    /**
     * @param bpmProcess
     *            null.
     */
    public void setBpmProcess(BpmProcess bpmProcess) {
        this.bpmProcess = bpmProcess;
    }

    /** @return null. */
    @Column(name = "TASK_DEFINITION_KEY", length = 200)
    public String getTaskDefinitionKey() {
        return this.taskDefinitionKey;
    }

    /**
     * @param taskDefinitionKey
     *            null.
     */
    public void setTaskDefinitionKey(String taskDefinitionKey) {
        this.taskDefinitionKey = taskDefinitionKey;
    }

    /** @return null. */
    @Column(name = "TYPE")
    public Integer getType() {
        return this.type;
    }

    /**
     * @param type
     *            null.
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /** @return null. */
    @Column(name = "RECEIVER", length = 200)
    public String getReceiver() {
        return this.receiver;
    }

    /**
     * @param receiver
     *            null.
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /** @return null. */
    @Column(name = "DUE_DATE", length = 50)
    public String getDueDate() {
        return this.dueDate;
    }

    /**
     * @param dueDate
     *            null.
     */
    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }
}
