package com.casic.patrol.internal.sendmail.persistence.domain;

// Generated by Hibernate Tools

import javax.persistence.*;

/**
 * SendmailAttachment .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "SENDMAIL_ATTACHMENT")
@SequenceGenerator(name = "CD_SEQ_SENDMAIL_ATTACHMENT",sequenceName = "CD_SEQ_SENDMAIL_ATTACHMENT",allocationSize = 1,initialValue = 1)
public class SendmailAttachment implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private SendmailTemplate sendmailTemplate;

    /** null. */
    private String name;

    /** null. */
    private String path;

    /** null. */
    private String tenantId;

    public SendmailAttachment() {
    }

    public SendmailAttachment(Long id) {
        this.id = id;
    }

    public SendmailAttachment(Long id, SendmailTemplate sendmailTemplate,
            String name, String path, String tenantId) {
        this.id = id;
        this.sendmailTemplate = sendmailTemplate;
        this.name = name;
        this.path = path;
        this.tenantId = tenantId;
    }

    /** @return null. */
    @Id
    @Column(name = "DBID", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CD_SEQ_SENDMAIL_ATTACHMENT")
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TEMPLATE_ID")
    public SendmailTemplate getSendmailTemplate() {
        return this.sendmailTemplate;
    }

    /**
     * @param sendmailTemplate
     *            null.
     */
    public void setSendmailTemplate(SendmailTemplate sendmailTemplate) {
        this.sendmailTemplate = sendmailTemplate;
    }

    /** @return null. */
    @Column(name = "ATTACH_NAME", length = 50)
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            null.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return null. */
    @Column(name = "PATH", length = 200)
    public String getPath() {
        return this.path;
    }

    /**
     * @param path
     *            null.
     */
    public void setPath(String path) {
        this.path = path;
    }

    /** @return null. */
    @Column(name = "TENANT_ID", length = 50)
    public String getTenantId() {
        return this.tenantId;
    }

    /**
     * @param tenantId
     *            null.
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }
}
