package com.casic.patrol.party.persistence.domain;

// Generated by Hibernate Tools

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * PartyEntity 组织实体.
 * 
 * @author Lingo
 */
@Entity
@Table(name="CD_PARTY_ENTITY")
@SequenceGenerator(name = "CD_PARTY_ENTITYIS",sequenceName = "CD_PARTY_ENTITYIS",allocationSize = 1,initialValue = 1)
public class PartyEntity implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;

    /** 外键，组织类型. */
    private PartyType partyType;

    /** 名称. */
    private String name;

    /** 外部引用. */
    private String ref;

    /** 租户. */
    private String tenantId;

    /** 区域. */
    private String region;

    /** 级别. */
    private Integer level;

    /** . */
    private Set<PartyStruct> parentStructs = new HashSet<com.casic.patrol.party.persistence.domain.PartyStruct>(0);

    /** . */
    private Set<PartyStruct> childStructs = new HashSet<PartyStruct>(0);

    public PartyEntity() {
    }

    public PartyEntity(Long id) {
        this.id = id;
    }

    public PartyEntity(Long id, PartyType partyType, String name, String ref,
            String tenantId, Integer level, Set<PartyStruct> parentStructs,
            Set<PartyStruct> childStructs) {
        this.id = id;
        this.partyType = partyType;
        this.name = name;
        this.ref = ref;
        this.tenantId = tenantId;
        this.level = level;
        this.parentStructs = parentStructs;
        this.childStructs = childStructs;
    }

    /** @return 主键. */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CD_PARTY_ENTITYIS")
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return 外键，组织类型. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TYPE_ID")
    public PartyType getPartyType() {
        return this.partyType;
    }

    /**
     * @param partyType
     *            外键，组织类型.
     */
    public void setPartyType(PartyType partyType) {
        this.partyType = partyType;
    }

    /** @return 名称. */
    @Column(name = "NAME", length = 100)
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            名称.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return 外部引用. */
    @Column(name = "REF", length = 100)
    public String getRef() {
        return this.ref;
    }

    /**
     * @param ref
     *            外部引用.
     */
    public void setRef(String ref) {
        this.ref = ref;
    }

    /** @return 租户. */
    @Column(name = "TENANT_ID", length = 50)
    public String getTenantId() {
        return this.tenantId;
    }

    /**
     * @param tenantId
     *            租户.
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /** @return 区域. */
    @Column(name = "REGION", length = 100)
    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    /** @return 级别. */
    @Column(name = "LEVEL1")
    public Integer getLevel() {
        return this.level;
    }

    /**
     * @param level
     *            级别.
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /** @return . */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "childEntity")
    public Set<PartyStruct> getParentStructs() {
        return this.parentStructs;
    }

    /**
     * @param parentStructs
     *            .
     */
    public void setParentStructs(Set<PartyStruct> parentStructs) {
        this.parentStructs = parentStructs;
    }

    /** @return . */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "parentEntity")
    public Set<PartyStruct> getChildStructs() {
        return this.childStructs;
    }

    /**
     * @param childStructs
     *            .
     */
    public void setChildStructs(Set<PartyStruct> childStructs) {
        this.childStructs = childStructs;
    }

}
