

INSERT INTO PORTAL_WIDGET(DBID,WIDGET_NAME,WIDGET_URL) VALUES(1,'待办任务','/rs/humantask/widget/personalTasks');
INSERT INTO PORTAL_WIDGET(DBID,WIDGET_NAME,WIDGET_URL) VALUES(2,'我的流程','/rs/bpm/widget/runningProcesses');
INSERT INTO PORTAL_WIDGET(DBID,WIDGET_NAME,WIDGET_URL) VALUES(3,'常用流程','/rs/bpm/widget/processes');


INSERT INTO PORTAL_INFO(DBID,USER_ID,COLUMN_LAYOUT,SHARED_STATUS,GLOBAL_STATUS) VALUES(1,NULL,'4-4-4','true','true');


INSERT INTO PORTAL_ITEM(DBID,ITEM_NAME,COLUMN_INDEX,ROW_INDEX,INFO_ID,WIDGET_ID) VALUES(1,'待办任务',1,1,1,1);
INSERT INTO PORTAL_ITEM(DBID,ITEM_NAME,COLUMN_INDEX,ROW_INDEX,INFO_ID,WIDGET_ID) VALUES(2,'我的流程',2,1,1,2);
-- INSERT INTO PORTAL_ITEM(DBID,ITEM_NAME,COLUMN_INDEX,ROW_INDEX,INFO_ID,WIDGET_ID) VALUES(3,'常用流程',3,1,1,3);

