

INSERT INTO BPM_CATEGORY(DBID,NAME,PRIORITY) VALUES(1,'常用流程',1);

INSERT INTO BPM_PROCESS(DBID,NAME,PRIORITY,DESCN,CATEGORY_ID,USE_TASK_CONF) VALUES(1,'事故处理流程',1,'通用事故处理流程',1,0);

UPDATE BPM_PROCESS SET CODE='surveillance' WHERE DBID=1;
